### PR TITLE
Added few German/French diacritical characters

### PR DESCRIPTION
**Pull request by 3d-gussner**
See 
https://docs.oracle.com/cd/E29584_01/webhelp/mdex_basicDev/src/rbdv_chars_mapping.html

### CODE REVIEW

**Comment by 3d-gussner** [comment]
@DRracer and @leptun 
Hi does it makes sense to make these kinds of PRs?

**Comment by leptun** [comment]
@3d-gussner I have no idea. Do the translation files include these characters. And if yes, then why were they left there in the first place?

**Comment by DRracer** [comment]
@3d-gussner of course, these are safety conditions that help to prevent errors in the (not-so-good) documented language translation process. 
And if you are asking whether to create a PR at all, or do a simple push, please feel free to push into the translation-doc branch directly (if possible). That's why I invited you as collaborators.
If there is a question or something to decide, do a PR, we may discuss it more easily.

**Review by DRracer — APPROVED** [review]

**Comment by 3d-gussner** [comment]
> And if yes, then why were they left there in the first place?



> @3d-gussner I have no idea. Do the translation files include these characters. And if yes, then why were they left there in the first place?

Hi @leptun, translators may forget that they are not allowed to use diacritical characters or just type as they normally do. Then the `.po` will contain unsupported characters. So it makes sense to replace all know unsupported characters.

**Comment by 3d-gussner** [comment]
> @3d-gussner of course, these are safety conditions that help to prevent errors in the (not-so-good) documented language translation process.
> And if you are asking whether to create a PR at all, or do a simple push, please feel free to push into the translation-doc branch directly (if possible). That's why I invited you as collaborators.
> If there is a question or something to decide, do a PR, we may discuss it more easily.

Good point. I will try to push more and just use PRs if I think we need a decision.

**Pull request merged**
