### PR TITLE
How-to add new language to Prusa Firmware ... Add Dutch translation

### PR DESCRIPTION
**Pull request by 3d-gussner**
I don't know if your MK3 branch is correct (as it is not up2date to origin), but i give it a try.

### CODE REVIEW

**Comment by DRracer** [comment]
@3d-gussner I'm afraid my MK3 hasn't been synced for a long time, I "live" in various branches :) . Please keep this PR, it is definitely very interesting. I'd like to finish the translations we already have in the FW, commit them for 3.8.1 and then we may prepare some more.
Please check the correct number of spaces in "Sound [assist]" and add Z-probe [5] as I did in my latest commit.

**Comment by 3d-gussner** [comment]
> @3d-gussner I'm afraid my MK3 hasn't been synced for a long time, I "live" in various branches :) . Please keep this PR, it is definitely very interesting. I'd like to finish the translations we already have in the FW, commit them for 3.8.1 and then we may prepare some more.
> Please check the correct number of spaces in "Sound [assist]" and add Z-probe [5] as I did in my latest commit.

@DRracer I feel the same ... switching between different branches isn't easy and keep all them up2date. 
The `Sound [assist]` and `Z-probe [5]` I found the very 1st time I was running my pre-release workprocess.
BTW. I think there is somewhere a bug with one of the scripts in lang folder...It didn't found one new message...But I can't remember which one it missed.

Do you need a hand with the translation? I saw you are using `%-16.16S%` and other methods to place thing correctly on the display.

**Comment by 3d-gussner** [comment]
Don't know where to put this again...I don't think i should open an issue on Prusa3d repository for this one.

During looking on other github repositories i follow I saw some using https://probot.github.io/apps/stale/ wouldn't that be great for Prusa3d? Lot of old issues and PRs just stay there and most times the issue owners "forgets" to close these.

**Comment by DRracer** [comment]
@3d-gussner I just merged the upstream MK3 and "our" translation-doc branch. It was quite a large amount of conflicts in ultralcd.cpp, can you please check if everything is ok?
I'd skip the PWR and BED translation for now, that's the only change.

probot.github.io : interesting tool, we'll look into it. Yes, there is a huge number of issues no-one is ever going to solve. And if the reporter really insists on the issue, he may reopen it, can't he?

**Comment by 3d-gussner** [comment]
@DRracer  wel done... I will do it tomorrow !

**Comment by 3d-gussner** [comment]
@DRracer opened a PR in the root as your MK3 branch is out of date :-)

**Pull request closed without merging**
